#ifndef SL_COMPONENT_CATALOG_H
#define SL_COMPONENT_CATALOG_H

// APIs present in project
#define SL_CATALOG_APP_ASSERT_PRESENT
#define SL_CATALOG_BLUETOOTH_FEATURE_ADVERTISER_PRESENT
#define SL_CATALOG_BLUETOOTH_FEATURE_CONNECTION_PRESENT
#define SL_CATALOG_BLUETOOTH_FEATURE_SCANNER_PRESENT
#define SL_CATALOG_BLUETOOTH_FEATURE_SM_PRESENT
#define SL_CATALOG_BLUETOOTH_PRESENT
#define SL_CATALOG_DEVICE_INIT_NVIC_PRESENT
#define SL_CATALOG_EMLIB_CORE_DEBUG_CONFIG_PRESENT
#define SL_CATALOG_GATT_CONFIGURATION_PRESENT
#define SL_CATALOG_MPU_PRESENT
#define SL_CATALOG_NVM3_PRESENT
#define SL_CATALOG_POWER_MANAGER_PRESENT
#define SL_CATALOG_PWM_PRESENT
#define SL_CATALOG_PWM_SERVO_PRESENT
#define SL_CATALOG_RAIL_LIB_PRESENT
#define SL_CATALOG_SE_MANAGER_PRESENT
#define SL_CATALOG_SLEEPTIMER_PRESENT
#define SL_CATALOG_SLI_PROTOCOL_CRYPTO_PRESENT

#endif // SL_COMPONENT_CATALOG_H
