#ifndef SMARTLOCK_COMPONENTS_TEMPERATURESENSOR_H
#define SMARTLOCK_COMPONENTS_TEMPERATURESENSOR_H

float readObjectTempC(void);
float readAmbientTempC(void);

#endif // SMARTLOCK_COMPONENTS_TEMPERATURESENSOR_H
